##Function to plot roc curves from pROC generated by our RF Classifier

ROC_plotter <- function(model, key, title, randModels = NA,  confLvl = 0.95){
  require(pROC)
  require(ggplot2)
  
  #Gather the model's votes and average them
  modelVotes <- model$votes
  modelVotes <- rowMeans(modelVotes)
  modelVotes <- data.frame(model = modelVotes, response = key)
  
  #Gather the random votes
  if(all(!is.na(randModels))){
    randVotes <- matrix(nrow = 121, ncol = length(randModels))
    #randVotes <- matrix(nrow = nrow(modelVotes), ncol = length(randModels))
    for(i in 1:length(randModels)){
      randVotes[,i] <- rowMeans(randModels[[i]]$votes) 
    }
    randVotes <- rowMeans(randVotes)
    randVotes <- data.frame(rand = randVotes, response = randKey)
  }
  
  #Plot the model
  rocObj <- plot(roc(response ~ model, modelVotes), 
                 print.auc = TRUE,
                 print.auc.y = 0.11,
                 print.auc.x = 0.3,
                 col = 'blue', 
                 xlim = c(1,0), 
                 ylim = c(0,1),
                 main = title)
  
  #add a confidence interval
  ciobj <- ci.se(rocObj, specificities = seq(0, 1, 0.05), conf.level = confLvl)
  plot(ciobj, type = 'shape', col = '#88BBD6AA')
  
  
  #pull the random votes from each model in the list of randoms if it exists
  if(!is.na(randModels)){
    
    #Plot the random
    rocObj <- plot(roc(response ~ rand, randVotes),
                   print.auc = T,
                   print.auc.y = 0.01,
                   print.auc.x = 0.3,
                   col = 'red',
                   add = T)
    #plot its confidence interval
    ciobj <- ci.se(rocObj, specificities = seq(0, 1, 0.05), conf.level = confLvl)
    plot(ciobj, type = 'shape', col = '#e06967AA')
  }
}

